# Generated by Django 5.2.15 on 2026-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'indexes': [models.Index(fields=['name'], name='weather_cit_name_db5943_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude', 'timestamp'], name='weather_wea_latitud_716b25_idx')],
                'constraints': [models.UniqueConstraint(fields=('latitude', 'longitude', 'timestamp'), name='unique_lat_lon_timestamp')],
            },
        ),
    ]
